runtime: python37
entrypoint: gunicorn -b :$PORT --timeout 240 -w 3 --worker-class gevent server.main:app
instance_class: F4
automatic_scaling:
  max_instances: 15
  max_concurrent_requests: 150

default_expiration: "5m"
handlers:
- url: /static
  static_dir: client/build/static
  secure: always
  expiration: "1m"
  http_headers:
    Cache-Control: public, max-age=10, s-max-age=10
    Strict-Transport-Security: max-age=63072000; includeSubDomains
- url: /.*
  script: auto
  secure: always
env_variables:
  GCP_PROJECT: wordle-386115
  FLASK_ENV: production
  FLASK_APP: server/main.py