runtime: python37
entrypoint: gunicorn -b :$PORT --timeout 240 -w 3 --worker-class gevent server.main:app
instance_class: F4
automatic_scaling:
  max_instances: 15
  max_concurrent_requests: 150

default_expiration: "5m"
handlers:
  # Serve React static files
  - url: /(.*\.(js|css|png|jpg|gif|ico|html|svg))
    static_files: client/build/\1
    upload: client/build/.*\.(js|css|png|jpg|gif|ico|html|svg)$
    secure: always
    http_headers:
      Strict-Transport-Security: "max-age=31536000; includeSubDomains"

  # Route all /api requests to the Flask server
  - url: /api/.*
    script: auto
    secure: always

  # Serve React index.html file for all other routes
  - url: /.*
    static_files: client/build/index.html
    upload: client/build/index.html
    secure: always
    http_headers:
      Strict-Transport-Security: "max-age=31536000; includeSubDomains"
env_variables:
  GCP_PROJECT: wordle-386115
  FLASK_ENV: production
  FLASK_APP: server/main.py
  OAUTHLIB_RELAX_TOKEN_SCOPE: 1
  APP_ROOT: /srv